name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get submodules
      run: git submodule update --init --recursive

    - name: Update apt
      run: sudo apt-get update --fix-missing
    
    - name: Install tree, gcc, make, xorg, libxext-dev & libbsd-dev
      run: sudo apt-get install tree gcc make xorg libxext-dev libbsd-dev

    - name: Install norminette
      run: pip install norminette

    - name: Tree
      run: tree

    - name: Run norminette
      run: norminette src include libs/libft/src libs/libft/include

    - name: Make program
      run: make

    - name: Re-make program
      run: make re

    - name: View Contents of Libft
      run: nm -C libs/libft/build/libft.a

    - name: View Contents of minilibx
      run: nm -C libs/minilibx/libmlx_Linux.a
