name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Get submodules
      run: git submodule update --init --recursive

    - name: Update apt
      run: sudo apt-get update --fix-missing
    
    - name: Install tree, gcc, make, xorg, libxext-dev & libbsd-dev
      run: sudo apt-get install tree gcc make xorg libxext-dev libbsd-dev

    - name: Install norminette
      run: pip install norminette

    - name: Run tree
      run: tree

    - name: Run norminette
      run: norminette src include libs/libft/src libs/libft/include

    - name: Make so_long
      run: make

    - name: Re-make so_long
      run: make re

    - name: View contents of libft
      run: nm -C libs/libft/build/libft.a

    - name: View contents of minilibx
      run: nm -C libs/minilibx/libmlx_Linux.a
    
    - name: View contents of so_long
      run: nm -C so_long
